# Default values for kube-broker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# set the namespace for all variables
namespace: crypto-broker

# sets the number of replicas, originally set to 1
replicaCount: 1

# Path to crypto profiles
profilesDir: /app/profiles

# This is for the secrets for pulling an image from a private repository
# imagePullSecrets: []

clientApp:
  name: client-app-js
  image:
    name: ghcr.io/open-crypto-broker/test-app-js
    tag: latest
    pullPolicy: IfNotPresent
  argHash:
    - --loop=1000
    - --profile=Default
    - hash
    - "ğ’®â„´ğ“‚â„¯ ğ’¶ğ“‡ğ’·ğ’¾ğ“‰ğ“‡ğ’¶ğ“‡ğ“ ğ’·ğ“ğ“‰â„´ğ“ˆ ğ“‰â„´ ğ’½ğ’¶ğ“ˆğ’½"
  argSign:
    - --loop=1000
    - --profile=Default
    - sign
    - --csr=/certificates/end-entity.csr
    - --caCert=/certificates/ca_cert.pem
    - --caKey=/certificates/private_key.pem

serverApp:
  name: server-app
  image:
    name: ghcr.io/open-crypto-broker/server
    tag: latest
    pullPolicy: IfNotPresent

volumes:
  - name: socket-volume
    emptyDir: {}
  - name: certs-volume
    configMap:
      name: "kube-broker-certificates"

volumeMounts:
  - name: socket-volume
    mountPath: /tmp
  - name: certs-volume
    mountPath: /certificates

imageCredentials:
  # Adjust this if any private image should be pulled automatically by the chart
  create: false
  secretName: example-secret
  registry: "TODO: add docker repository"
  username: ""             # Placeholder, will be overridden with enviroment variable
  password: ""             # Placeholder, will be overridden with enviroment variable
  email: ""                # Placeholder, will be overridden with enviroment variable

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials
  automount: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
