name: Task Continuous Integration

on:
  push:
    branches: [ main, dev ]
  pull_request:
  schedule:
    - cron: '0 3 * * *' # Run this pipeline every day at 03:00

jobs:
  task-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run end-to-end tests
        run: task test-clis
